name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.6.0"
          host: linux
          target: desktop

      - name: Add Qt to PATH
        run: echo "$QT_PATH/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgl1-mesa-dev libboost-all-dev

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cmake --build build --config Release --parallel 2
